# Generated by Django 5.0.4 on 2026-04-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PICKUP', 'Đang chờ lấy hàng'), ('PACKAGING', 'Đang đóng gói hàng'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã nhận hàng'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING_PICKUP', max_length=20),
        ),
    ]
