# Generated by Django 5.0.4 on 2026-03-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
