# Generated by Django 5.0.4 on 2026-03-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reference_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
