# Generated by Django 4.2.27 on 2026-01-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_artisan_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-quantity_sold']},
        ),
    ]
