# Generated by Django 5.0.4 on 2026-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HIDDEN', 'Hidden')], default='ACTIVE', max_length=10),
        ),
    ]
