version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tramhon_odoo_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432" 
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  web:
    image: odoo:16.0
    container_name: tramhon_odoo16
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data: