# Generated by Django 5.0.4 on 2026-03-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Customer'), ('ARTISAN', 'Artisan'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
