# Generated by Django 5.0.4 on 2026-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ARTISAN', 'Artisan'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10),
        ),
    ]
